name: MLOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  train-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Descargar archivos Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Verificar dataset
        run: |
          ls -lh data/raw
          head -n 1 data/raw/creditcard.csv

      - name: Ejecutar pipeline DVC
        env:
            MLFLOW_TRACKING_URI: sqlite:///mlflow.db
        run: |
          dvc repro

      - name: Validar métricas mínimas
        run: |
          python src/validate.py --metrics artifacts/metrics.json

      - name: Mostrar métricas
        run: |
          cat artifacts/metrics.json
